-- MEMORY-002 P1 · One retrieval surface over snippets and memory items.
--
-- The plan (docs/MEMORY_002_PLAN.md) requires one knowledge ecosystem without a
-- parallel store. This is the mechanism: a read-only view that PROJECTS the
-- context sources into a common shape. It stores nothing, it copies nothing, and
-- every row keeps exactly one home. Snippet bodies stay in `snippets`, memory
-- bodies stay in `memory_shards`, and writes never pass through here.
--
-- ⚠ security_invoker = true IS THE WHOLE POINT, NOT A DETAIL.
--
-- A Postgres view defaults to running with its OWNER's rights, which would
-- bypass the RLS on the underlying tables and hand every caller everyone's rows.
-- With security_invoker set, each source table's own policy applies to whoever
-- is querying. Authorization is therefore COMPOSED rather than unified: this
-- view never decides access, it inherits whatever the caller could already see.
-- Snippets keep the folder ACL, memory keeps personal ownership, and no third
-- authorization model is introduced.
--
-- ⚠⚠ A SECURITY DEFINER FUNCTION QUERYING THIS VIEW DEFEATS THAT.
--
-- security_invoker resolves against the role executing the query. Inside a
-- SECURITY DEFINER function that role is the definer (postgres), which bypasses
-- RLS, so such a function would see every user's rows. Any function reading this
-- view MUST be SECURITY INVOKER. That is not a limitation to work around; it is
-- why the MCP token path (which needs a definer, because auth.uid() is null
-- there) is deliberately a separate later phase with its own soak, rather than a
-- side effect of shipping search.
--
-- PROMPTS ARE ABSENT, ON PURPOSE. A prompt is an instruction you run, not
-- knowledge to inject. In a context package it competes with the live
-- instruction, and a model given two sets of instructions follows neither
-- reliably; the failure is silent and reads as the model being unpredictable.
-- The exclusion is structural rather than a filter column, because a filter is
-- an invitation to flip it. Prompts remain fully reachable AS prompts through
-- the prompt library. See P-1 in the plan.
--
-- Lives in `app`, which PostgREST does not expose, so the view is not reachable
-- as a REST resource. Retrieval reaches it through functions added in P2.

create or replace view app.knowledge_index
with (security_invoker = true) as

  -- ── Memory items ───────────────────────────────────────────────────────────
  select
    'memory'::text                as kind,
    m.id::text                    as source_id,
    m.name                        as title,
    m.summary                     as summary,
    m.body                        as body,
    -- Already generated by the database as ceil(char_length(body) / 4.0).
    coalesce(m.token_estimate, 0) as tokens,
    m.updated_at                  as updated_at,
    m.user_id                     as owner_id,
    -- A correlated subquery rather than a LEFT JOIN plus GROUP BY: when a caller
    -- selects only ids and titles, Postgres drops an unreferenced subquery from
    -- the target list, so listing costs nothing for labels. A GROUP BY would be
    -- paid on every query whether the column was wanted or not.
    array(
      select ml.label_id
      from public.memory_shard_labels ml
      where ml.shard_id = m.id
      order by ml.label_id
    )                             as label_ids
  from public.memory_shards m
  where m.deleted_at is null

  union all

  -- ── Snippets ───────────────────────────────────────────────────────────────
  select
    'snippet'::text as kind,
    s.id            as source_id,
    s.title         as title,
    -- Snippets carry no summary column. The first non-empty line is the closest
    -- honest equivalent: it is what a human wrote first and what a reader scans.
    -- Trimmed to the summary length memory items are capped at, so both kinds
    -- cost about the same to list.
    left(
      coalesce(
        nullif(btrim(split_part(s.body, E'\n', 1)), ''),
        btrim(s.body)
      ),
      280
    )               as summary,
    s.body          as body,
    -- Must equal CHARS_PER_TOKEN in app/src/lib/memory/engine.ts and the
    -- token_estimate generated column, or a budget means two different things
    -- depending on which kind filled it.
    ceil(char_length(s.body) / 4.0)::int as tokens,
    s.updated_at    as updated_at,
    s.user_id       as owner_id,
    array(
      select sl.label_id
      from public.snippet_labels sl
      where sl.snippet_id = s.id
      order by sl.label_id
    )               as label_ids
  from public.snippets s
  -- is_active is the user saying "do not use this", so an inactive snippet must
  -- not be retrievable either. is_malformed is deliberately NOT filtered: it
  -- reports a broken template, which affects expansion rather than the value of
  -- the text as background knowledge.
  where s.is_active;

comment on view app.knowledge_index is
  'MEMORY-002 P1 · Retrieval projection over snippets and memory items. security_invoker: composes each source''s RLS, never widens it. Prompts excluded by design (instructions, not context). Callers MUST be SECURITY INVOKER.';

-- No grant to anon. The view is not a REST resource and the token path cannot
-- use it safely until the folder ACL is parameterised (P6).
revoke all on app.knowledge_index from public, anon;
grant select on app.knowledge_index to authenticated, service_role;
