import { useEffect, useMemo, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { formatDistanceToNow } from 'date-fns';
import {
  AlertCircle,
  ArrowLeft,
  Clock,
  Coins,
  FileText,
  FileUp,
  Layers,
  Pencil,
  Pin,
  Plus,
  Trash2,
  Upload,
} from 'lucide-react';
import { EmptyState } from '@/components/layout/EmptyState';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { cn } from '@/lib/utils';
import { ItemEditor } from '@/features/memory/ItemEditor';
import { HistoryPanel, type HistoryEntry } from '@/features/history/HistoryPanel';
import { SpaceIcon } from '@/features/memory/spaceIcon';
import { KIND_LABEL } from '@/features/memory/kindLabel';
import { TrashPanel } from '@/features/memory/TrashPanel';
import { buildTrashRows, describePieces, type TrashRow } from '@/features/memory/trashRows';
import { useMemoryStore } from '@/stores/memoryStore';
import { useSearchStore } from '@/stores/searchStore';
import { useUiStore } from '@/stores/uiStore';
import { normalizeQuery, scoreMemoryItem } from '@/lib/searchIndex';
import { memoryApi } from '@/lib/api/memoryApi';
import { ACCEPTED_EXTENSIONS, DocumentTextError } from '@/lib/documentText';
import type { MemoryDocument, MemoryItem } from '@/types/database';

// One space and its items.
//
// The three tiles are Items, Tokens and Updated. Tokens rather than bytes on
// purpose: a byte count is a number nobody acts on, while the token total is the
// exact figure a step's budget is measured against, generated by the same column
// the engine reads.
//
// The page lists live rows only. Trashed ones live in the trash panel, so the
// lists never mix what the assistant can read with what it cannot.

/**
 * What to say when a file does not go in.
 *
 * Each reason has a different next step, and "upload failed" hides all of them:
 * a scan needs retyping or a different export, an unsupported file needs
 * converting, a large one needs splitting. The reader's own message already
 * names the file, so these read as a sentence about that file.
 */
function uploadFailureMessage(fileName: string, err: unknown): string {
  if (err instanceof DocumentTextError) {
    if (err.reason === 'no-text') {
      return `${fileName} has no text to copy. If it is a scan or a photo of a page, the words are a picture, so they have to be typed in.`;
    }
    if (err.reason === 'unsupported') {
      return `${fileName} is not a kind we can read. PDF, Word (.docx), text and Markdown work.`;
    }
    if (err.reason === 'too-large') return `${fileName} is over 20 MB. Split it and upload the parts.`;
    return `${fileName} could not be opened. It may be damaged or password-protected.`;
  }
  return err instanceof Error ? err.message : `${fileName} could not be added.`;
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

/** One uploaded file, above the pieces it became. */
function DocumentCard({
  document: doc,
  onOpen,
  onTrash,
}: {
  document: MemoryDocument;
  onOpen: () => void;
  onTrash: () => void;
}) {
  return (
    <Card className="flex items-start justify-between gap-3 p-4">
      <div className="flex min-w-0 items-center gap-2.5">
        <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-[10px] bg-bg-alt text-ink-muted">
          <FileUp className="h-4 w-4" />
        </div>
        <div className="min-w-0">
          <button
            type="button"
            onClick={onOpen}
            className="block max-w-full truncate text-left text-sm font-semibold text-ink hover:text-primary"
            title={`Open ${doc.name}`}
          >
            {doc.name}
          </button>
          <div className="mt-0.5 flex items-center gap-2 text-[11px] text-ink-subtle">
            <span className="tabular-nums">{describePieces(doc.chunk_count)}</span>
            <span className="tabular-nums">{formatBytes(doc.byte_size)}</span>
            <span>Added {formatDistanceToNow(new Date(doc.created_at), { addSuffix: true })}</span>
          </div>
        </div>
      </div>

      <div className="flex shrink-0 items-center gap-1">
        <button
          type="button"
          onClick={onTrash}
          title="Move this file and its pieces to the trash"
          className="rounded-[8px] p-1.5 text-ink-subtle transition-colors hover:bg-danger-bg hover:text-danger"
        >
          <Trash2 className="h-4 w-4" />
        </button>
      </div>
    </Card>
  );
}

function StatTile({
  label,
  value,
  icon: Icon,
}: {
  label: string;
  value: string;
  icon: typeof Layers;
}) {
  return (
    <Card className="flex items-center gap-3 p-4">
      <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-[10px] bg-primary-light text-primary">
        <Icon className="h-4 w-4" />
      </div>
      <div className="min-w-0">
        <div className="truncate text-lg font-bold tabular-nums leading-tight text-ink">
          {value}
        </div>
        <div className="text-xs text-ink-subtle">{label}</div>
      </div>
    </Card>
  );
}

function ItemCard({
  item,
  onEdit,
  onTrash,
}: {
  item: MemoryItem;
  onEdit: () => void;
  onTrash: () => void;
}) {
  const [expanded, setExpanded] = useState(false);

  return (
    <Card className="flex flex-col gap-2 p-4">
      <div className="flex items-start justify-between gap-3">
        <div className="flex min-w-0 items-center gap-2.5">
          <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-[10px] bg-bg-alt text-ink-muted">
            <FileText className="h-4 w-4" />
          </div>
          <div className="min-w-0">
            <div className="flex items-center gap-2">
              <span className="truncate text-sm font-semibold text-ink">{item.name}</span>
              {item.pinned ? (
                <Pin className="h-3 w-3 shrink-0 fill-current text-primary" aria-label="Always attached" />
              ) : null}
            </div>
            <div className="mt-0.5 flex items-center gap-2 text-[11px] text-ink-subtle">
              <span className="rounded-full bg-bg-alt px-2 py-0.5 font-medium">
                {KIND_LABEL[item.kind]}
              </span>
              <span className="tabular-nums">{item.token_estimate} tokens</span>
              <span>
                Updated {formatDistanceToNow(new Date(item.updated_at), { addSuffix: true })}
              </span>
            </div>
          </div>
        </div>

        <div className="flex shrink-0 items-center gap-1">
          <button
            type="button"
            onClick={onEdit}
            title="Edit"
            className="rounded-md p-1.5 text-ink-subtle hover:bg-bg-alt hover:text-ink"
          >
            <Pencil className="h-3.5 w-3.5" />
          </button>
          <button
            type="button"
            onClick={onTrash}
            title="Move to trash"
            className="rounded-md p-1.5 text-ink-subtle hover:bg-danger-bg hover:text-danger"
          >
            <Trash2 className="h-3.5 w-3.5" />
          </button>
        </div>
      </div>

      {item.summary ? (
        <p className="text-sm text-ink-muted">{item.summary}</p>
      ) : (
        <p className="text-sm italic text-ink-subtle">
          No summary. Add one so this can be listed without loading its body.
        </p>
      )}

      <div>
        <button
          type="button"
          onClick={() => setExpanded((value) => !value)}
          className="text-xs font-medium text-primary hover:underline"
        >
          {expanded ? 'Hide body' : 'Show body'}
        </button>
        {expanded ? (
          <pre className="mt-2 max-h-64 overflow-auto whitespace-pre-wrap rounded-[10px] bg-bg-alt p-3 font-mono text-xs leading-relaxed text-ink">
            {item.body}
          </pre>
        ) : null}
      </div>
    </Card>
  );
}

export function MemorySpacePage() {
  const { spaceId = '' } = useParams<{ spaceId: string }>();

  const spaces = useMemoryStore((s) => s.spaces);
  const loaded = useMemoryStore((s) => s.loaded);
  const items = useMemoryStore((s) => s.items);
  const loadingItems = useMemoryStore((s) => s.loadingItems);
  const error = useMemoryStore((s) => s.error);
  const loadSpaces = useMemoryStore((s) => s.loadSpaces);
  const loadItems = useMemoryStore((s) => s.loadItems);
  const saveItem = useMemoryStore((s) => s.saveItem);
  const trashItem = useMemoryStore((s) => s.trashItem);
  const restoreItem = useMemoryStore((s) => s.restoreItem);
  const showToast = useUiStore((s) => s.showToast);

  const [editorTarget, setEditorTarget] = useState<'new' | MemoryItem | null>(null);
  // The one search bar in the header owns the text (SEARCH-001).
  const query = useSearchStore((s) => s.query);
  const clearSearch = useSearchStore((s) => s.clear);

  const documents = useMemoryStore((s) => s.documents);
  const importing = useMemoryStore((s) => s.importing);
  const loadDocuments = useMemoryStore((s) => s.loadDocuments);
  const importDocument = useMemoryStore((s) => s.importDocument);
  const trashDocument = useMemoryStore((s) => s.trashDocument);
  const restoreDocument = useMemoryStore((s) => s.restoreDocument);
  const fileInputRef = useRef<HTMLInputElement | null>(null);
  const [dragging, setDragging] = useState(false);

  const deleteForever = useMemoryStore((s) => s.deleteForever);
  const [trashOpen, setTrashOpen] = useState(false);

  const versions = useMemoryStore((s) => s.versions);
  const versionsLoading = useMemoryStore((s) => s.versionsLoading);
  const loadVersions = useMemoryStore((s) => s.loadVersions);
  const restoreVersion = useMemoryStore((s) => s.restoreVersion);
  // The item whose history is open. Held here rather than in the store because
  // it is one panel on one page, and the store already carries the versions.
  const [historyItem, setHistoryItem] = useState<MemoryItem | null>(null);

  const historyEntries = useMemo<HistoryEntry[]>(
    () =>
      versions.map((version) => ({
        id: version.id,
        versionNumber: version.version_number,
        editorDisplay: version.editor_display,
        createdAt: version.created_at,
        body: version.body,
        note: version.edit_note,
      })),
    [versions],
  );

  async function handleRestoreVersion(entry: HistoryEntry) {
    const version = versions.find((candidate) => candidate.id === entry.id);
    if (!historyItem || !version) return;
    try {
      await restoreVersion(historyItem, version);
      showToast(`Restored to v${version.version_number} — saved as the latest version.`);
      setHistoryItem(null);
      setEditorTarget(null);
    } catch (err) {
      showToast(err instanceof Error ? err.message : 'Could not restore that version.', 'error');
    }
  }

  useEffect(() => {
    if (!loaded) void loadSpaces();
  }, [loaded, loadSpaces]);

  useEffect(() => {
    if (spaceId) {
      void loadItems(spaceId);
      void loadDocuments(spaceId);
    }
  }, [spaceId, loadItems, loadDocuments]);

  const space = spaces.find((candidate) => candidate.id === spaceId) ?? null;

  // Tiles count live items only: a trashed item is not attachable, so counting
  // it would overstate what the space holds.
  const live = useMemo(() => items.filter((item) => item.deleted_at === null), [items]);
  const liveDocuments = useMemo(
    () => documents.filter((doc) => doc.deleted_at === null),
    [documents],
  );
  const trashRows = useMemo(() => buildTrashRows(items, documents), [items, documents]);

  // A space had no way to filter its own contents before the one search bar
  // (SEARCH-001). The tiles above stay whole-space counts: they describe the
  // space, not the search.
  const needle = normalizeQuery(query);
  const visible = useMemo(() => {
    if (needle === '') return live;
    return live.filter((item) => scoreMemoryItem(item, needle, space?.name ?? null) > 0);
  }, [live, needle, space]);
  const tokens = useMemo(
    () => live.reduce((total, item) => total + item.token_estimate, 0),
    [live],
  );

  function reportFailure(err: unknown, fallback: string) {
    showToast(err instanceof Error ? err.message : fallback, 'error');
  }

  function restoreItemNow(item: MemoryItem) {
    restoreItem(item.id).then(
      () => showToast(`"${item.name}" restored.`),
      (err: unknown) => reportFailure(err, 'Could not restore that item.'),
    );
  }

  function restoreDocumentNow(doc: MemoryDocument) {
    restoreDocument(doc.id).then(
      () => showToast(`${doc.name} is back`),
      (err: unknown) => reportFailure(err, 'Could not restore that file.'),
    );
  }

  /** The row leaves the list at once; the toast offers the way back. */
  function trashItemNow(item: MemoryItem) {
    trashItem(item.id).then(
      () =>
        showToast(`"${item.name}" moved to trash.`, 'success', {
          label: 'Undo',
          onClick: () => restoreItemNow(item),
        }),
      (err: unknown) => reportFailure(err, 'Could not trash that item.'),
    );
  }

  function trashDocumentNow(doc: MemoryDocument) {
    trashDocument(doc.id).then(
      () =>
        showToast(
          `${doc.name} and its ${describePieces(doc.chunk_count)} moved to trash.`,
          'success',
          { label: 'Undo', onClick: () => restoreDocumentNow(doc) },
        ),
      (err: unknown) => reportFailure(err, 'Could not remove that file.'),
    );
  }

  function restoreRow(row: TrashRow) {
    if (row.kind === 'file') restoreDocumentNow(row.document);
    else restoreItemNow(row.item);
  }

  async function deleteRow(row: TrashRow) {
    try {
      await deleteForever(
        spaceId,
        row.kind === 'file'
          ? { itemIds: [], documentIds: [row.id] }
          : { itemIds: [row.id], documentIds: [] },
      );
      showToast(`${row.kind === 'file' ? row.name : `"${row.name}"`} deleted permanently.`);
    } catch (err) {
      reportFailure(err, 'Could not delete that permanently.');
    }
  }

  async function emptyTrash() {
    try {
      await deleteForever(spaceId, {
        itemIds: trashRows.filter((row) => row.kind === 'item').map((row) => row.id),
        documentIds: trashRows.filter((row) => row.kind === 'file').map((row) => row.id),
      });
      showToast('Trash emptied.');
      setTrashOpen(false);
    } catch (err) {
      reportFailure(err, 'Could not empty the trash.');
    }
  }

  /**
   * Files are taken one at a time rather than in parallel: each one is read,
   * split and written in a single transaction, and three of those at once would
   * make the progress line meaningless and the failure message ambiguous.
   */
  async function importFiles(list: FileList | null) {
    if (!list || !spaceId) return;
    for (const file of Array.from(list)) {
      try {
        const result = await importDocument(file, spaceId);
        const pieces = describePieces(result.chunkCount);
        showToast(
          result.forced > 0
            ? `${file.name} added as ${pieces}. ${result.forced} had to be cut mid-paragraph.`
            : `${file.name} added as ${pieces}`,
        );
      } catch (err) {
        showToast(uploadFailureMessage(file.name, err), 'error');
      }
    }
  }

  async function openDocument(doc: MemoryDocument) {
    try {
      window.open(await memoryApi.documentUrl(doc.storage_path), '_blank', 'noopener');
    } catch {
      showToast('Could not open that file.', 'error');
    }
  }

  if (loaded && !space) {
    return (
      <div>
        <Link
          to="/memory"
          className="mb-6 inline-flex items-center gap-1.5 text-sm text-ink-muted hover:text-ink"
        >
          <ArrowLeft className="h-4 w-4" />
          Brains
        </Link>
        <EmptyState
          title="That Brain is not here"
          description="It may have been moved to the trash, or the link may be stale."
        />
      </div>
    );
  }

  return (
    <div>
      <Link
        to="/memory"
        className="mb-4 inline-flex items-center gap-1.5 text-sm text-ink-muted hover:text-ink"
      >
        <ArrowLeft className="h-4 w-4" />
        Brains
      </Link>

      <div className="mb-6 flex items-end justify-between gap-4">
        <div className="flex min-w-0 items-center gap-3">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-[12px] bg-primary-light text-primary">
            <SpaceIcon icon={space?.ico} className="h-5 w-5" />
          </div>
          <div className="min-w-0">
            <h1 className="truncate text-2xl font-bold tracking-tight text-ink">
              {space?.name ?? 'Brain'}
            </h1>
            {space?.description ? (
              <p className="mt-0.5 truncate text-sm text-ink-muted">{space.description}</p>
            ) : null}
          </div>
        </div>
        <Button onClick={() => setEditorTarget('new')}>
          <Plus className="h-4 w-4" />
          Add text
        </Button>
      </div>

      {error ? (
        <div className="mb-4 flex items-start gap-2 rounded-[12px] bg-danger-bg px-3 py-2 text-sm text-danger">
          <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />
          <span>{error}</span>
        </div>
      ) : null}

      <div className="mb-6 grid grid-cols-3 gap-4">
        <StatTile label="Items" value={String(live.length)} icon={Layers} />
        <StatTile label="Tokens" value={tokens.toLocaleString()} icon={Coins} />
        <StatTile
          label="Last updated"
          value={
            space ? formatDistanceToNow(new Date(space.updated_at), { addSuffix: false }) : '—'
          }
          icon={Clock}
        />
      </div>

      <div className="mb-6 grid grid-cols-2 gap-4">
        <button
          type="button"
          onClick={() => setEditorTarget('new')}
          className="flex items-center justify-center gap-2 rounded-[16px] border border-dashed border-primary/50 bg-primary-bg/40 px-6 py-6 text-sm font-semibold text-primary transition-colors hover:bg-primary-bg"
        >
          <Pencil className="h-4 w-4" />
          Add text
        </button>
        <button
          type="button"
          onClick={() => fileInputRef.current?.click()}
          onDragOver={(event) => {
            event.preventDefault();
            setDragging(true);
          }}
          onDragLeave={() => setDragging(false)}
          onDrop={(event) => {
            event.preventDefault();
            setDragging(false);
            void importFiles(event.dataTransfer.files);
          }}
          disabled={importing !== null}
          className={cn(
            'flex items-center justify-center gap-2 rounded-[16px] border border-dashed px-6 py-6 text-sm font-semibold transition-colors',
            importing !== null
              ? 'cursor-wait border-line bg-card text-ink-subtle'
              : dragging
                ? 'border-primary bg-primary-bg text-primary'
                : 'border-primary/50 bg-primary-bg/40 text-primary hover:bg-primary-bg',
          )}
        >
          <Upload className="h-4 w-4" />
          {importing !== null ? `Reading ${importing}…` : 'Upload file'}
        </button>
        <input
          ref={fileInputRef}
          type="file"
          multiple
          accept={ACCEPTED_EXTENSIONS}
          className="hidden"
          onChange={(event) => {
            void importFiles(event.target.files);
            // Cleared so picking the same file twice in a row still fires.
            event.target.value = '';
          }}
        />
      </div>

      {liveDocuments.length > 0 ? (
        <div className="mb-6">
          <h2 className="mb-3 text-sm font-semibold text-ink">Files ({liveDocuments.length})</h2>
          <div className="grid grid-cols-2 gap-3">
            {liveDocuments.map((doc) => (
              <DocumentCard
                key={doc.id}
                document={doc}
                onOpen={() => void openDocument(doc)}
                onTrash={() => trashDocumentNow(doc)}
              />
            ))}
          </div>
        </div>
      ) : null}

      <div className="mb-3 flex items-center justify-between">
        <h2 className="text-sm font-semibold text-ink">
          Contents ({visible.length})
        </h2>
        <button
          type="button"
          onClick={() => setTrashOpen(true)}
          className="inline-flex items-center gap-1.5 rounded-[10px] border border-line bg-card px-3 py-1.5 text-xs font-medium text-ink-muted transition-colors hover:bg-bg-alt"
        >
          <Trash2 className="h-3.5 w-3.5" />
          {trashRows.length > 0 ? `Trash (${trashRows.length})` : 'Trash'}
        </button>
      </div>

      {loadingItems && items.length === 0 ? (
        <div className="flex items-center justify-center py-16 text-sm text-ink-subtle">
          Loading items…
        </div>
      ) : visible.length === 0 ? (
        <EmptyState
          icon={FileText}
          title={live.length === 0 ? 'Nothing in here yet' : 'Nothing matches'}
          description={
            live.length === 0
              ? 'Add one fact. Keep it to a single idea, and give it a summary so it can be listed without being read.'
              : 'Try a different search, or clear the search box in the header.'
          }
          action={
            live.length === 0 ? (
              <Button onClick={() => setEditorTarget('new')}>
                <Plus className="h-4 w-4" />
                Add text
              </Button>
            ) : (
              <Button variant="ghost" size="sm" onClick={clearSearch}>
                Clear search
              </Button>
            )
          }
        />
      ) : (
        <div className="flex flex-col gap-3">
          {visible.map((item) => (
            <ItemCard
              key={item.id}
              item={item}
              onEdit={() => setEditorTarget(item)}
              onTrash={() => trashItemNow(item)}
            />
          ))}
        </div>
      )}

      <ItemEditor
        target={editorTarget}
        spaceId={spaceId}
        onClose={() => setEditorTarget(null)}
        onSave={saveItem}
        onOpenHistory={(item) => {
          setHistoryItem(item);
          void loadVersions(item.id);
        }}
      />

      <HistoryPanel
        open={historyItem !== null}
        subject={historyItem?.name ?? null}
        noun="item"
        entries={historyEntries}
        loading={versionsLoading}
        onClose={() => setHistoryItem(null)}
        onRestore={handleRestoreVersion}
      />

      <TrashPanel
        open={trashOpen}
        spaceName={space?.name ?? 'Brain'}
        rows={trashRows}
        onClose={() => setTrashOpen(false)}
        onRestore={restoreRow}
        onDelete={deleteRow}
        onEmpty={emptyTrash}
      />
    </div>
  );
}
