import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { formatDistanceToNow } from 'date-fns';
import {
  AlertCircle,
  ArrowLeft,
  Clock,
  Coins,
  FileText,
  Layers,
  Pencil,
  Pin,
  Plus,
  RotateCcw,
  Trash2,
  Upload,
} from 'lucide-react';
import { EmptyState } from '@/components/layout/EmptyState';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { cn } from '@/lib/utils';
import { ItemEditor } from '@/features/memory/ItemEditor';
import { SpaceIcon } from '@/features/memory/spaceIcon';
import { useMemoryStore } from '@/stores/memoryStore';
import { useUiStore } from '@/stores/uiStore';
import type { MemoryItem, MemoryItemKind } from '@/types/database';

// One space and its items.
//
// The three tiles are Items, Tokens and Updated. Tokens rather than bytes on
// purpose: a byte count is a number nobody acts on, while the token total is the
// exact figure a step's budget is measured against, generated by the same column
// the engine reads.

const KIND_LABEL: Record<MemoryItemKind, string> = {
  fact: 'Fact',
  note: 'Note',
  document: 'Document',
  conversation: 'Conversation',
};

function StatTile({
  label,
  value,
  icon: Icon,
}: {
  label: string;
  value: string;
  icon: typeof Layers;
}) {
  return (
    <Card className="flex items-center gap-3 p-4">
      <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-[10px] bg-primary-light text-primary">
        <Icon className="h-4 w-4" />
      </div>
      <div className="min-w-0">
        <div className="truncate text-lg font-bold tabular-nums leading-tight text-ink">
          {value}
        </div>
        <div className="text-xs text-ink-subtle">{label}</div>
      </div>
    </Card>
  );
}

function ItemCard({
  item,
  onEdit,
  onTrash,
  onRestore,
}: {
  item: MemoryItem;
  onEdit: () => void;
  onTrash: () => void;
  onRestore: () => void;
}) {
  const [expanded, setExpanded] = useState(false);
  const trashed = item.deleted_at !== null;

  return (
    <Card className={cn('flex flex-col gap-2 p-4', trashed && 'opacity-60')}>
      <div className="flex items-start justify-between gap-3">
        <div className="flex min-w-0 items-center gap-2.5">
          <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-[10px] bg-bg-alt text-ink-muted">
            <FileText className="h-4 w-4" />
          </div>
          <div className="min-w-0">
            <div className="flex items-center gap-2">
              <span className="truncate text-sm font-semibold text-ink">{item.name}</span>
              {item.pinned ? (
                <Pin className="h-3 w-3 shrink-0 fill-current text-primary" aria-label="Always attached" />
              ) : null}
            </div>
            <div className="mt-0.5 flex items-center gap-2 text-[11px] text-ink-subtle">
              <span className="rounded-full bg-bg-alt px-2 py-0.5 font-medium">
                {KIND_LABEL[item.kind]}
              </span>
              <span className="tabular-nums">{item.token_estimate} tokens</span>
              <span>
                Updated {formatDistanceToNow(new Date(item.updated_at), { addSuffix: true })}
              </span>
            </div>
          </div>
        </div>

        <div className="flex shrink-0 items-center gap-1">
          {trashed ? (
            <button
              type="button"
              onClick={onRestore}
              title="Restore"
              className="rounded-md p-1.5 text-ink-subtle hover:bg-bg-alt hover:text-ink"
            >
              <RotateCcw className="h-3.5 w-3.5" />
            </button>
          ) : (
            <>
              <button
                type="button"
                onClick={onEdit}
                title="Edit"
                className="rounded-md p-1.5 text-ink-subtle hover:bg-bg-alt hover:text-ink"
              >
                <Pencil className="h-3.5 w-3.5" />
              </button>
              <button
                type="button"
                onClick={onTrash}
                title="Move to trash"
                className="rounded-md p-1.5 text-ink-subtle hover:bg-danger-bg hover:text-danger"
              >
                <Trash2 className="h-3.5 w-3.5" />
              </button>
            </>
          )}
        </div>
      </div>

      {item.summary ? (
        <p className="text-sm text-ink-muted">{item.summary}</p>
      ) : (
        <p className="text-sm italic text-ink-subtle">
          No summary. Add one so this can be listed without loading its body.
        </p>
      )}

      <div>
        <button
          type="button"
          onClick={() => setExpanded((value) => !value)}
          className="text-xs font-medium text-primary hover:underline"
        >
          {expanded ? 'Hide body' : 'Show body'}
        </button>
        {expanded ? (
          <pre className="mt-2 max-h-64 overflow-auto whitespace-pre-wrap rounded-[10px] bg-bg-alt p-3 font-mono text-xs leading-relaxed text-ink">
            {item.body}
          </pre>
        ) : null}
      </div>
    </Card>
  );
}

export function MemorySpacePage() {
  const { spaceId = '' } = useParams<{ spaceId: string }>();

  const spaces = useMemoryStore((s) => s.spaces);
  const loaded = useMemoryStore((s) => s.loaded);
  const items = useMemoryStore((s) => s.items);
  const loadingItems = useMemoryStore((s) => s.loadingItems);
  const showTrashed = useMemoryStore((s) => s.showTrashed);
  const error = useMemoryStore((s) => s.error);
  const loadSpaces = useMemoryStore((s) => s.loadSpaces);
  const loadItems = useMemoryStore((s) => s.loadItems);
  const setShowTrashed = useMemoryStore((s) => s.setShowTrashed);
  const saveItem = useMemoryStore((s) => s.saveItem);
  const trashItem = useMemoryStore((s) => s.trashItem);
  const restoreItem = useMemoryStore((s) => s.restoreItem);
  const showToast = useUiStore((s) => s.showToast);

  const [editorTarget, setEditorTarget] = useState<'new' | MemoryItem | null>(null);

  useEffect(() => {
    if (!loaded) void loadSpaces();
  }, [loaded, loadSpaces]);

  useEffect(() => {
    if (spaceId) void loadItems(spaceId);
  }, [spaceId, loadItems]);

  const space = spaces.find((candidate) => candidate.id === spaceId) ?? null;

  // Tiles count live items only, even when the trash is on screen: a trashed
  // item is not attachable, so counting it would overstate what the space holds.
  const live = useMemo(() => items.filter((item) => item.deleted_at === null), [items]);
  const tokens = useMemo(
    () => live.reduce((total, item) => total + item.token_estimate, 0),
    [live],
  );
  const trashedCount = items.length - live.length;

  async function run(action: Promise<unknown>, success: string, failure: string) {
    try {
      await action;
      showToast(success);
    } catch (err) {
      showToast(err instanceof Error ? err.message : failure, 'error');
    }
  }

  if (loaded && !space) {
    return (
      <div>
        <Link
          to="/memory"
          className="mb-6 inline-flex items-center gap-1.5 text-sm text-ink-muted hover:text-ink"
        >
          <ArrowLeft className="h-4 w-4" />
          Memory
        </Link>
        <EmptyState
          title="That space is not here"
          description="It may have been moved to the trash, or the link may be stale."
        />
      </div>
    );
  }

  return (
    <div>
      <Link
        to="/memory"
        className="mb-4 inline-flex items-center gap-1.5 text-sm text-ink-muted hover:text-ink"
      >
        <ArrowLeft className="h-4 w-4" />
        Memory
      </Link>

      <div className="mb-6 flex items-end justify-between gap-4">
        <div className="flex min-w-0 items-center gap-3">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-[12px] bg-primary-light text-primary">
            <SpaceIcon icon={space?.ico} className="h-5 w-5" />
          </div>
          <div className="min-w-0">
            <h1 className="truncate text-2xl font-bold tracking-tight text-ink">
              {space?.name ?? 'Space'}
            </h1>
            {space?.description ? (
              <p className="mt-0.5 truncate text-sm text-ink-muted">{space.description}</p>
            ) : null}
          </div>
        </div>
        <Button onClick={() => setEditorTarget('new')}>
          <Plus className="h-4 w-4" />
          Add text
        </Button>
      </div>

      {error ? (
        <div className="mb-4 flex items-start gap-2 rounded-[12px] bg-danger-bg px-3 py-2 text-sm text-danger">
          <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />
          <span>{error}</span>
        </div>
      ) : null}

      <div className="mb-6 grid grid-cols-3 gap-4">
        <StatTile label="Items" value={String(live.length)} icon={Layers} />
        <StatTile label="Tokens" value={tokens.toLocaleString()} icon={Coins} />
        <StatTile
          label="Last updated"
          value={
            space ? formatDistanceToNow(new Date(space.updated_at), { addSuffix: false }) : '—'
          }
          icon={Clock}
        />
      </div>

      <div className="mb-6 grid grid-cols-2 gap-4">
        <button
          type="button"
          onClick={() => setEditorTarget('new')}
          className="flex items-center justify-center gap-2 rounded-[16px] border border-dashed border-primary/50 bg-primary-bg/40 px-6 py-6 text-sm font-semibold text-primary transition-colors hover:bg-primary-bg"
        >
          <Pencil className="h-4 w-4" />
          Add text
        </button>
        <div
          title="Uploads arrive with document chunking"
          className="flex cursor-not-allowed items-center justify-center gap-2 rounded-[16px] border border-dashed border-line bg-card px-6 py-6 text-sm font-medium text-ink-subtle"
        >
          <Upload className="h-4 w-4" />
          Upload file (not yet)
        </div>
      </div>

      <div className="mb-3 flex items-center justify-between">
        <h2 className="text-sm font-semibold text-ink">
          Contents ({live.length})
        </h2>
        <button
          type="button"
          onClick={() => setShowTrashed(!showTrashed)}
          className={cn(
            'inline-flex items-center gap-1.5 rounded-[10px] border px-3 py-1.5 text-xs font-medium transition-colors',
            showTrashed
              ? 'border-primary-bdr bg-primary-bg text-primary'
              : 'border-line bg-card text-ink-muted hover:bg-bg-alt',
          )}
        >
          <Trash2 className="h-3.5 w-3.5" />
          {showTrashed ? `Trash shown (${trashedCount})` : 'View trash'}
        </button>
      </div>

      {loadingItems && items.length === 0 ? (
        <div className="flex items-center justify-center py-16 text-sm text-ink-subtle">
          Loading items…
        </div>
      ) : items.length === 0 ? (
        <EmptyState
          icon={FileText}
          title="Nothing in here yet"
          description="Add one fact. Keep it to a single idea, and give it a summary so it can be listed without being read."
          action={
            <Button onClick={() => setEditorTarget('new')}>
              <Plus className="h-4 w-4" />
              Add text
            </Button>
          }
        />
      ) : (
        <div className="flex flex-col gap-3">
          {items.map((item) => (
            <ItemCard
              key={item.id}
              item={item}
              onEdit={() => setEditorTarget(item)}
              onTrash={() =>
                void run(
                  trashItem(item.id),
                  `"${item.name}" moved to trash.`,
                  'Could not trash that item.',
                )
              }
              onRestore={() =>
                void run(
                  restoreItem(item.id),
                  `"${item.name}" restored.`,
                  'Could not restore that item.',
                )
              }
            />
          ))}
        </div>
      )}

      <ItemEditor
        target={editorTarget}
        spaceId={spaceId}
        onClose={() => setEditorTarget(null)}
        onSave={saveItem}
      />
    </div>
  );
}
